config/routes.rb
Rails.application.routes.draw do
 root to: 'homes#top'
 devise_for :users
 
 resources :users, only: [:index, :show, :edit, :update]
 resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
 get "/home/about" => "homes#about", as: "about"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    belongs_to :user
    
    validates :title, :body,  presence: true
    validates :body, length: { maximum: 200 }
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  
  has_many :books, dependent: :destroy
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

validates :name, presence: true
validates :name, uniqueness: true
validates :name, length: { in: 2..20 }
validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top, :about]
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
        user_path(current_user)
    end
    
    def after_sign_out_path_for(resource)
        flash[:notice] = "Signed out successfully."
        root_path
    end
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
 
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] ="You have created book successfully."
      redirect_to book_path(@book.id)
    else
       @user = current_user
       @books = Book.all
       render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id]) 
    @user = @books.user
  end

  def edit
    @books = Book.find(params[:id])
  end
  
  def update
    @books = Book.find(params[:id])
   if @books.update(book_params)
    flash[:notice] ="You have update book successfully."
    redirect_to book_path(@books.id)
   else
    render :edit
   end
  end
  
  def destroy
    @books = Book.find(params[:id])
    @books.destroy
    redirect_to books_path
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    user = book.user
    unless user == current_user
      redirect_to books_path
    end
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice] ="You have update user successfully."
     redirect_to user_path(current_user)
    else
     render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_booklist.html.erb
  <h2 class="mt-3">New book</h2>

  <%= form_with model: book do |f| %>
 
   <h7>Title</h7><br>
   <%= f.text_field :title %><br>
  
   <h7>Opinion</h7><br>
   <%= f.text_area :body %><br>
  
   <%= f.submit 'Create Book', class: 'btn btn-success' %>
  
   <% end %>

app/views/books/edit.html.erb
  <% if @books.errors.any? %>
   <%= @books.errors.count %>errors prohibitea this obj from being saved:
   <ul>
       <% @books.errors.full_messages.each do |message| %>
   <li>
    <%= message %>
   </li>
   <% end %>
   </ul>
  <% end %>

<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   
   <h1>Editing Book</h1>

  <%= form_with model: @books do |f| %>
   <h7>Title</h7><br>
   <%= f.text_field :title %><br>
   <h7>Opinion</h7><br>
   <%= f.text_area :body %><br>
 
<%= f.submit 'Update Book', class: 'btn btn-success' %><br>

<%= link_to "Show", book_path(@books.id) %>
<%= link_to "Back", books_path %>

<% end %>

app/views/books/index.html.erb
<%= render 'users/userlist', user: @user, book: @book %>
<%= render '/books/booklist', book: @book %>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>

<table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th colspan="3"></th>
     </tr>
    </thead>
    
     <tbody>
    <% @books.each do |book| %>
     
      <tr>
        <td><%= link_to user_path(book.user.id) do %>
        <p><%= image_tag book.user.get_profile_image(80,80) %></p>
        <% end %></td>
        <td><%= link_to book_path(book.id) do %>
        <p><%= book.title %></p>
        <% end %></td>
        <td>
        <p><%= book.body %></p></td>
      </tr>
    <% end %>
    </tbody>
   </table>
  </div>

app/views/books/show.html.erb
<%= render '/users/userlist', user: @user, book: @book %>
<%= render '/books/booklist', book: @book %>

<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>

<div>
 <p><%= image_tag @books.user.get_profile_image(80,80) %></p>
 <%= link_to user_path(@books.user.id) do %>
 <p><%= @books.user.name %></p>
 <% end %>
 <%= link_to book_path(@books.id) do %>
  <p><%= @books.title %></p>
 <% end %>
 <p><%= @books.body %></p>
 
 
 <% if @books.user == current_user %>
 <%= link_to "Edit", edit_book_path(@books.id), class: 'btn btn-success' %>
 <%= link_to "Destroy", book_path(@books), class: 'btn btn-danger', method: :delete, "data-confirm" => "本当に消しますか？" %>
 <% end %>

 </div>
 </div>
 

app/views/homes/about.html.erb
<div class="container">
    <div class="row">
        <h1 class="px-3 mx-auto">welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>

<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
            
            <p>In<i class="fas fa-book"></i><strong>Bookers</strong>,</p>
            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p>about various books</p>
            
            <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                    <a class="btn btn-info btn-sm btn-block md-3 sign_in" href="/users/sign_in">Log in</a>
                </div>
                <div class="row">
                    <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  

  <body>
      <header>
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <div class="container">
                <a class="navbar-brand" href="/"><span>Bookers</span></a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNavDropdown">
                      <ul class="navbar-nav ml-auto">
                      <% if user_signed_in? %>
                      <li class="nav-item">
                          <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                          <i class="fas fa-home"></i>Home
                          <% end %>
                      </li>
                      <li class="nav-item">
                          <%= link_to users_path, class: "nav-link text-light" do %>
                          <i class="fas fa-users"></i>Users
                          <% end %>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link text-light" href="/books">
                          <i class="fas fa-book-open"></i>Books
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link text-light" rel-"nofollow" data-method="delete" href="/users/sign_out">
                          <i class="fas fa-sign-out-alt"></i>Log out
                          </a>
                      </li>
                     <% else %>
                     <li class=nav-item>
                         <a class="nav-link text-light" href="/">
                         <i class="fas fa-home"></i>Home
                         </a>
                     </li>
                     <li class="nav-item">
                         <a class="nav-link text-light" href="/home/about">
                         <i class="fas fa-link"></i>About
                         </a>
                     </li>
                     <li class="nav-item">
                         <a class="nav-link text-light" href="/users/sign_up">
                         <i class="fas fa-user-plus"></i>Sign up
                         </a>
                     </li>
                     <li class="nav-item">
                         <a class="nav-link text-light" href="/users/sign_in">
                         <i class="fas fa-sign-in-alt"></i>Log in
                         </a>
                     </li>
                     <% end %>
                     </ul>
                   </div>
               </div>
            </nav>
        </header>
        
      <main>
        <div class="container px-5 px-sm-o">
          <div class="row">
            <div class="col-md-3">
                <%= yield %>
            </div>
          </div>
        </div>
      </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>

</html>

app/views/users/_userlist.html.erb
  <div>
      <%= flash[:notice] %>
  </div>
  
  <% if book.errors.any? %>
   <%= book.errors.count %>errors prohibitea this obj from being saved:
   <ul>
       <% book.errors.full_messages.each do |message| %>
   <li>
    <%= message %>
   </li>
   <% end %>
   </ul>
  <% end %>

   <%= image_tag user.get_profile_image(100,100) %>
   <table class="table">
    <tbody>
     <tr></tr>
     <tr>
      <th>name</th>
      <th><%= user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
     </tr>
    </tbody>
   </table>
  
   <div class="row">
     <%= link_to edit_user_path(user), class: "btn btn-outline-secondary" do %>
     <i class="fas fa-user-cog"></i>
     <% end %>
   </div>

app/views/users/edit.html.erb
 <% if @user.errors.any? %>
   <%= @user.errors.count %>errors prohibitea this obj from being saved:
   <ul>
       <% @user.errors.full_messages.each do |message| %>
   <li>
    <%= message %>
   </li>
   <% end %>
   </ul>
  <% end %>

<h2>User info</h2>
<%= form_with model: @user do |f| %>

<label for="inputName">Name</label><br>
<%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %><br>
<label for="inputImage">Image</label><br>
<%= f.file_field :profile_image, placeholder:"プロフィール画像", accept:"image/*" %><br>
<label for="inputIntroduction">Introduction</label><br>
<%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介" %><br>
<%= f.submit "Update User", class: 'btn btn-secondary' %>

<% end %>

app/views/users/index.html.erb
<%= render 'users/userlist', user: @user, book: @book %>
<%= render '/books/booklist', book: @book %>

<div class="col-md-8 offset-md-1">
<h2>Users</h2>

 <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th colspan="3"></th>
     </tr>
    </thead>

  <tbody>
 <% @users.each do |user| %>
    
    <tr>
      <td><%= image_tag user.get_profile_image(80,80) %></td>
      <td><%= user.name %> </td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
    
  <% end %>
 </tbody>
</table>
</div>

app/views/users/show.html.erb
<%= render 'users/userlist', user: @user, book:@book %>
<%= render '/books/booklist', book: @book %>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
 <table class="table table-hover table-inverse">
  <% @books.each do |book| %>
  
   <thead>
    <tr>
     <th></th>
     <th>Title</t>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
   </thead>
   
   <tbody>
    <tr>
     <td><%= link_to user_path(@user.id) do %>
      <%= image_tag @user.get_profile_image(80,80) %>
      <% end %>
     </td>
     <td><span><%= link_to book.title,"/books/#{book.id}" %></span></td>
     <td><p><%= book.body %></p></td>
    </tr>
   </tbody>
  
  <% end %>
 </table>
 </div>
 